#!/bin/bash

echo "🚀 Waddiny Notification Testing Script"
echo "======================================"

# Check if devices are connected
echo "📱 Checking connected devices..."
flutter devices

echo ""
echo "🧪 Testing Scenarios:"
echo "====================="
echo ""
echo "1. 📱 iOS Device Setup:"
echo "   - Open the Waddiny app on your iPhone/iPad"
echo "   - Grant notification permissions when prompted"
echo "   - Go to Settings > Notifications > Waddiny"
echo "   - Enable all notification types"
echo ""
echo "2. 🧪 Test Local Notifications:"
echo "   - Open the app and navigate to any trip screen"
echo "   - Tap the notification icon in the app bar"
echo "   - Use the test screen to verify notifications work"
echo ""
echo "3. 🧪 Test Trip Status Notifications:"
echo "   - Create a trip on one device (user account)"
echo "   - Accept the trip on another device (driver account)"
echo "   - Verify user gets 'Driver Accepted Your Trip!' notification"
echo "   - Update trip status to 'In Way'"
echo "   - Verify user gets 'Driver is on the Way!' notification"
echo "   - Update trip status to 'Arrived'"
echo "   - Verify user gets 'Driver Has Arrived!' notification"
echo ""
echo "4. 🧪 Test New Trip Notifications:"
echo "   - Create a new trip on user device"
echo "   - Verify all active drivers get 'New Trip Available!' notification"
echo ""
echo "5. 🧪 Test Background Notifications:"
echo "   - Open app and navigate to a trip"
echo "   - Press home button to minimize app"
echo "   - Create a trip from another device"
echo "   - Verify notification appears on lock screen"
echo ""
echo "🔧 Troubleshooting Commands:"
echo "============================"
echo ""
echo "View logs:"
echo "flutter logs --device-id 00008110-001059A93EF3801E  # iPhone"
echo "flutter logs --device-id 00008030-00090502269B402E  # iPad"
echo ""
echo "Rebuild and reinstall:"
echo "flutter clean && flutter pub get && flutter build ios --release"
echo "flutter install --device-id 00008110-001059A93EF3801E"
echo ""
echo "Check notification permissions:"
echo "Settings > Notifications > Waddiny"
echo ""
echo "✅ Ready to test! Open the app on your devices and follow the scenarios above." 