name: waddiny
description: A professional taxi booking app for users and drivers.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3
  flutter_polyline_points: ^2.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  http: ^1.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.1.0
  sensors_plus: ^4.0.2
  image: ^4.1.7
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  package_info_plus: ^8.0.2
  intl: ^0.20.2
  flutter_local_notifications: ^16.3.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - .env 
    - assets/images/car_marker.png
    - assets/images/waddiny.png

flutter_native_splash:
  color: "#000000"
  image: assets/images/waddiny.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/waddiny.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/waddiny.png" 